# Site settings
name: Deploy Jekyll with GitHub Pages dependencies preinstalled
title:
email: "gdscudg@gmail.com"
description: > # this means to ignore newlines until "baseurl:"
baseurl: "https://gdscudg.github.io/"
url: "" # the base hostname & protocol for your site

twitter_username: gdscudg
github_username: gdscudg
instagram_username: gdsc_udg
linktree_username: gdscudg

# Build settings
markdown: kramdown
